version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    working_dir: /web
    ports:
      - "80:5000"
    volumes:
       - "../:/web"
    command: "python -u /web/src/app.py"
    # env_file:
    #   - ../config/.env